import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

describe('bookkeeping frontend source', () => {
  const app = readFileSync(join(process.cwd(), 'src', 'App.tsx'), 'utf8')
  const layout = readFileSync(join(process.cwd(), 'src', 'components', 'Layout.tsx'), 'utf8')
  const page = readFileSync(join(process.cwd(), 'src', 'pages', 'Bookkeeping.tsx'), 'utf8')
  const api = readFileSync(join(process.cwd(), 'src', 'services', 'api.ts'), 'utf8')

  it('registers bookkeeping subroutes and left menu entries', () => {
    expect(app).toContain("const Bookkeeping = lazy(() => import('./pages/Bookkeeping'))")
    expect(app).toContain('path="/bookkeeping/*"')
    expect(layout).toContain("key: '/bookkeeping'")
    expect(layout).toContain("key: '/bookkeeping/rolling'")
    expect(layout).toContain("key: '/bookkeeping/crown/accounts'")
    expect(layout).toContain("key: '/bookkeeping/whatsapp/groups'")
    expect(layout).toContain('赛前工作台')
    expect(layout).toContain('滚球工作台')
    expect(layout).toContain('皇冠账号管理')
    expect(layout).toContain('WhatsApp 群配置')
    expect(layout).toContain('皇冠投注记录')
    expect(layout).toContain('WhatsApp 订单中心')
    expect(layout).toContain('对账中心')
    expect(layout).toContain('报表中心')
  })

  it('shows a simplified prematch bill generation center', () => {
    expect(page).toContain('赛前工作台')
    expect(page).toContain('上游订单、下游拆单、公司跟单与赛前结算中心')
    expect(page).toContain('renderPreMatchTimeBar')
    expect(page).toContain('扫描开始')
    expect(page).toContain('扫描结束')
    expect(page).toContain('renderPreMatchActions')
    expect(page).toContain('扫描群聊')
    expect(page).toContain('重新扫描')
    expect(page).toContain('生成上游群账单')
    expect(page).toContain('生成下游群账单（退水前）')
    expect(page).toContain('生成下游群账单（退水后）')
    expect(page).toContain('生成公司跟单表')
    expect(page).not.toContain('生成退水表')
    expect(page).not.toContain('生成亏水表')
    expect(page).toContain('生成公司总盈亏表')
    expect(page).toContain('一键生成全部文件')
    expect(page).toContain('上游总下注额')
    expect(page).toContain('下游总投放额')
    expect(page).toContain('公司跟单额')
    expect(page).toContain('下游退水金额')
    expect(page).toContain('盈亏水金额')
    expect(page).toContain('公司总盈利')
    expect(page).toContain('preMatchSummaryItems')
    expect(page).toContain('preMatchReportActions')
    expect(page).toContain('rollingReportActions')
    expect(page).toContain('下游群账单（退水前）')
    expect(page).toContain('下游群账单（退水后）')
    expect(page).not.toContain("rebate: '退水表'")
    expect(page).not.toContain("water_loss: '亏水表'")
    expect(page).not.toContain('下游群主单')
    expect(page).toContain('上游群账单')
    expect(page).toContain('公司跟单表')
    expect(page).toContain('renderMetricBlock')
    expect(page).toContain('renderDashboardPage')
    expect(page).toContain('renderCrownAccountsPage')
    expect(page).toContain('renderGeneratedFilesSection')
    expect(page).toContain('清除生成文件')
    expect(page).toContain('clearGeneratedFiles')
    expect(page).not.toContain('renderPrematchOrderSummary')
    expect(page).not.toContain('renderPrematchMatchDetail')
    expect(page).not.toContain('renderCompanyFollowSection')
    expect(page).not.toContain('renderWaterLossSection')
    expect(page).not.toContain('renderPrematchSettlementSection')
    expect(page).not.toContain('renderExceptionSection')
    expect(page).not.toContain('renderOrderDrawer')
    expect(page).not.toContain('<Tabs')
    expect(page).toContain("renderHeader('赛前工作台', '上游订单、下游拆单、公司跟单与赛前结算中心')")
    expect(page).not.toContain('OpenClaw')
  })

  it('shows a simplified rolling bill generation center', () => {
    expect(page).toContain("if (clean.startsWith('/bookkeeping/rolling')) return 'rolling'")
    expect(page).toContain("renderHeader('滚球工作台'")
    expect(page).toContain('rollingReportActions')
    expect(page).toContain("{ workspaceType: 'rolling', reportType: 'rolling_group_orders', label: '生成滚球群账单' }")
    expect(page).toContain("{ workspaceType: 'rolling', reportType: 'crown_wagers', label: '生成皇冠注单表' }")
    expect(page).toContain("{ workspaceType: 'rolling', reportType: 'rolling_profit', label: '生成滚球盈亏表' }")
    expect(page).toContain("{ workspaceType: 'rolling', reportType: 'rolling_excel', label: '一键生成全部文件' }")
    expect(page).toContain('扫描滚球群')
    expect(page).toContain('抓取皇冠注单')
    expect(page).toContain('preMatchReportActions')
    expect(page).not.toContain("preMatchReportActions: Array<{ workspaceType: WorkspaceType; reportType: ReportType; label: string }> = [\n  { workspaceType: 'rolling', reportType: 'crown_wagers'")
    expect(page).toContain("workspaceType: 'rolling'")
    expect(page).toContain("workspaceType: 'prematch'")
    expect(page).toContain('rollingSummaryItems')
    expect(page).toContain('滚球群总投注额')
    expect(page).toContain('皇冠总下注额')
    expect(page).toContain('滚球群结算盈亏')
    expect(page).toContain('皇冠实际盈亏')
    expect(page).toContain('公司滚球净利润')
    expect(page).not.toContain('renderRollingOrderSummary')
    expect(page).not.toContain('renderRollingCrownSummary')
    expect(page).not.toContain('renderRollingReconciliation')
    expect(page).not.toContain('renderRollingProfitSection')
    expect(page).not.toContain('renderRollingExceptionSection')
  })

  it('keeps report buttons off non-workspace pages', () => {
    expect(page).toContain('actions: ReportAction[] = []')
    expect(page).toContain("renderHeader('皇冠账号', '单独管理 Crown 账号、登录测试和抓取状态')")
    expect(page).toContain("renderHeader('WhatsApp群聊', '读取本机 WhatsApp 群聊，设置上游、下游、公司跟单、滚球或忽略')")
    expect(page).toContain("renderHeader('Crown投注', '查看每个 Crown 账号抓到的投注记录')")
    expect(page).toContain("renderHeader('WhatsApp订单', '上游大单和下游小单统一查看')")
    expect(page).toContain("renderHeader('对账结果', 'WhatsApp订单、Crown投注和利润差异')")
    expect(page).toContain("renderHeader('Excel报表', '每天生成的完整账目文件')")
  })

  it('adds whatsapp group sync and settlement controls', () => {
    expect(page).toContain('同步本机群聊')
    expect(page).toContain('刷新登录状态')
    expect(page).toContain('QRCode')
    expect(page).toContain('待设置')
    expect(page).toContain('公司跟单群')
    expect(page).toContain('滚球群')
    expect(page).toContain('货币')
    expect(page).toContain('汇率')
    expect(page).toContain('退水')
    expect(page).toContain('退水（格）')
    expect(page).not.toContain('退水比例')
    expect(page).not.toContain('退水方式')
    expect(page).not.toContain('只输退水')
    expect(page).not.toContain('输赢都退')
    expect(page).not.toContain('走水也退')
    expect(page).toContain('rebatePoints')
    expect(page).toContain('exchangeRate')
    expect(page).toContain('RMB')
    expect(page).toContain('USDT')
  })

  it('shows configured upstream downstream and company follow groups on the dashboard', () => {
    expect(page).toContain('群聊配置')
    expect(page).toContain('上游群')
    expect(page).toContain('下游群')
    expect(page).toContain('公司跟单群')
    expect(page).toContain('公司跟单额')
    expect(page).not.toContain('群聊概况')
    expect(page).not.toContain('groupOverviewItems')
    expect(page).not.toContain('groupSettlementColumns')
  })

  it('calls the bookkeeping API namespace', () => {
    expect(api).toContain('bookkeeping:')
    expect(api).toContain('/bookkeeping/dashboard')
    expect(api).toContain('/bookkeeping/crown/accounts/list')
    expect(api).toContain('/bookkeeping/crown/wagers/import')
    expect(api).toContain('/bookkeeping/whatsapp/bootstrap')
    expect(api).toContain('/bookkeeping/whatsapp/status')
    expect(api).toContain('/bookkeeping/whatsapp/chats/sync')
    expect(api).toContain('/bookkeeping/whatsapp/scan')
    expect(api).toContain('/bookkeeping/whatsapp/orders/import')
    expect(api).toContain('/bookkeeping/tasks/run')
    expect(api).toContain('/bookkeeping/tasks/generated-files/clear')
    expect(api).toContain('/bookkeeping/tasks/${taskId}/download')
    expect(api).toContain('workspaceType?:')
    expect(api).not.toContain('openclaw')
    expect(api).not.toContain('OpenClaw')
  })

  it('wires prematch and rolling scan buttons to the whatsapp reader', () => {
    expect(page).toContain('scanWhatsappMessages')
    expect(page).toContain("workspaceType: 'prematch'")
    expect(page).toContain("workspaceType: 'rolling'")
    expect(page).toContain('扫描完成')
    expect(page).not.toContain("noticeWorkInProgress('扫描群聊')")
    expect(page).not.toContain("noticeWorkInProgress('重新扫描')")
    expect(page).not.toContain("noticeWorkInProgress('扫描滚球群')")
  })
})
