import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

describe('bookkeeping frontend source', () => {
  const app = readFileSync(join(process.cwd(), 'src', 'App.tsx'), 'utf8')
  const layout = readFileSync(join(process.cwd(), 'src', 'components', 'Layout.tsx'), 'utf8')
  const page = readFileSync(join(process.cwd(), 'src', 'pages', 'Bookkeeping.tsx'), 'utf8')
  const api = readFileSync(join(process.cwd(), 'src', 'services', 'api.ts'), 'utf8')

  it('registers bookkeeping subroutes and left menu entries', () => {
    expect(app).toContain("const Bookkeeping = lazy(() => import('./pages/Bookkeeping'))")
    expect(app).toContain('path="/bookkeeping/*"')
    expect(layout).toContain("key: '/bookkeeping'")
    expect(layout).toContain("key: '/bookkeeping/rolling'")
    expect(layout).toContain("key: '/bookkeeping/crown/accounts'")
    expect(layout).toContain("key: '/bookkeeping/whatsapp/groups'")
    expect(layout).toContain("key: '/bookkeeping/telegram/groups'")
    expect(layout).toContain('赛前工作台')
    expect(layout).toContain('滚球工作台')
    expect(layout).toContain('皇冠账号管理')
    expect(layout).toContain('WhatsApp 群配置')
    expect(layout).toContain('Telegram 群配置')
    expect(layout).toContain("key: '/bookkeeping/crown/wagers'")
    expect(layout).toContain("key: '/bookkeeping/prematch/reconciliation'")
    expect(layout).toContain("key: '/bookkeeping/rolling/reconciliation'")
    expect(layout).toContain('皇冠投注中心')
    expect(layout).toContain('赛前对账中心')
    expect(layout).toContain('滚球对账中心')
    expect(layout).not.toContain('皇冠投注记录')
    expect(layout).not.toContain('WhatsApp 订单中心')
    expect(layout).toContain('报表中心')
  })

  it('shows a simplified prematch bill generation center', () => {
    expect(page).toContain('赛前工作台')
    expect(page).toContain('上游订单、下游拆单、公司跟单与赛前结算中心')
    expect(page).toContain('renderPreMatchTimeBar')
    expect(page).toContain('扫描开始')
    expect(page).toContain('扫描结束')
    expect(page).toContain('renderPreMatchActions')
    expect(page).toContain('扫描WhatsApp赛前群')
    expect(page).toContain('重扫WhatsApp赛前群')
    expect(page).toContain('扫描TG赛前群')
    expect(page).toContain('重扫TG赛前群')
    expect(page).toContain('抓取赛果')
    expect(page).toContain('fetchTitan007Scores')
    expect(page).toContain("{ workspaceType: 'prematch', reportType: 'upstream_orders', label: '赛前上游各群表格' }")
    expect(page).toContain("{ workspaceType: 'prematch', reportType: 'downstream_orders', label: '赛前下游各群表格' }")
    expect(page).toContain("{ workspaceType: 'prematch', reportType: 'prematch_settlement', label: '盈亏水表格' }")
    expect(page).not.toContain('生成退水表')
    expect(page).not.toContain('生成亏水表')
    expect(page).toContain("{ workspaceType: 'prematch', reportType: 'prematch_profit', label: '公司盈亏表格' }")
    expect(page).toContain("{ workspaceType: 'prematch', reportType: 'prematch_excel', label: '一键生成' }")
    expect(page).not.toContain('生成上游群账单')
    expect(page).not.toContain('生成下游群账单（退水前）')
    expect(page).not.toContain('生成下游群账单（退水后）')
    expect(page).not.toContain('生成公司跟单表')
    expect(page).not.toContain('生成公司总盈亏表')
    expect(page).not.toContain('一键生成全部文件')
    expect(page).toContain('上游总下注额')
    expect(page).toContain('下游总投放额')
    expect(page).toContain('公司跟单额')
    expect(page).not.toContain('下游退水金额')
    expect(page).toContain('盈亏水金额')
    expect(page).toContain('公司总盈利')
    expect(page).toContain('preMatchSummaryItems')
    expect(page).toContain('preMatchReportActions')
    expect(page).toContain('rollingReportActions')
    expect(page).toContain('赛前下游各群表格')
    expect(page).not.toContain('downstream_before_rebate')
    expect(page).not.toContain('downstream_after_rebate')
    expect(page).not.toContain("rebate: '退水表'")
    expect(page).not.toContain("water_loss: '亏水表'")
    expect(page).not.toContain('下游群主单')
    expect(page).toContain('赛前上游各群表格')
    expect(page).toContain('公司跟单表')
    expect(page).toContain('renderMetricBlock')
    expect(page).toContain('renderDashboardPage')
    expect(page).toContain('renderCrownAccountsPage')
    expect(page).toContain('renderGeneratedFilesSection')
    expect(page).toContain('清除生成文件')
    expect(page).toContain('clearGeneratedFiles')
    expect(page).not.toContain('renderPrematchOrderSummary')
    expect(page).not.toContain('renderPrematchMatchDetail')
    expect(page).not.toContain('renderCompanyFollowSection')
    expect(page).not.toContain('renderWaterLossSection')
    expect(page).not.toContain('renderPrematchSettlementSection')
    expect(page).not.toContain('renderExceptionSection')
    expect(page).not.toContain('renderOrderDrawer')
    expect(page).not.toContain('<Tabs')
    expect(page).toContain("renderHeader('赛前工作台', '上游订单、下游拆单、公司跟单与赛前结算中心')")
    expect(page).not.toContain('OpenClaw')
  })

  it('shows a simplified rolling bill generation center', () => {
    expect(page).toContain("if (clean.startsWith('/bookkeeping/rolling')) return 'rolling'")
    expect(page).toContain("renderHeader('滚球工作台'")
    expect(page).toContain('rollingReportActions')
    expect(page).toContain("{ workspaceType: 'rolling', reportType: 'rolling_upstream_orders', label: '滚球上游各群表格' }")
    expect(page).toContain("{ workspaceType: 'rolling', reportType: 'rolling_downstream_orders', label: '滚球下游各群表格' }")
    expect(page).toContain("{ workspaceType: 'rolling', reportType: 'rolling_water', label: '盈亏水表格' }")
    expect(page).toContain("{ workspaceType: 'rolling', reportType: 'rolling_profit', label: '公司盈亏表格' }")
    expect(page).toContain("{ workspaceType: 'rolling', reportType: 'rolling_excel', label: '一键生成' }")
    expect(page).not.toContain("{ workspaceType: 'rolling', reportType: 'rolling_group_orders', label: '生成滚球群账单' }")
    expect(page).not.toContain("{ workspaceType: 'rolling', reportType: 'crown_wagers', label: '生成皇冠注单表' }")
    expect(page).not.toContain("{ workspaceType: 'rolling', reportType: 'rolling_profit', label: '生成滚球盈亏表' }")
    expect(page).not.toContain("{ workspaceType: 'rolling', reportType: 'rolling_excel', label: '一键生成全部文件' }")
    expect(page).toContain('扫描WhatsApp滚球群')
    expect(page).toContain('扫描TG滚球群')
    expect(page).toContain('抓取赛果')
    expect(page).toContain('抓取皇冠注单')
    expect(page).toContain('preMatchReportActions')
    expect(page).not.toContain("preMatchReportActions: Array<{ workspaceType: WorkspaceType; reportType: ReportType; label: string }> = [\n  { workspaceType: 'rolling', reportType: 'crown_wagers'")
    expect(page).toContain("workspaceType: 'rolling'")
    expect(page).toContain("workspaceType: 'prematch'")
    expect(page).toContain('rollingSummaryItems')
    expect(page).toContain('滚球群总投注额')
    expect(page).toContain('皇冠总下注额')
    expect(page).toContain('滚球群结算盈亏')
    expect(page).toContain('皇冠实际盈亏')
    expect(page).toContain('公司滚球净利润')
    expect(page).not.toContain('renderRollingOrderSummary')
    expect(page).not.toContain('renderRollingCrownSummary')
    expect(page).not.toContain('renderRollingProfitSection')
    expect(page).not.toContain('renderRollingExceptionSection')
  })

  it('keeps report buttons off non-workspace pages', () => {
    expect(page).toContain('actions: ReportAction[] = []')
    expect(page).toContain("renderHeader('皇冠账号', '单独管理 Crown 账号、登录测试和抓取状态')")
    expect(page).toContain("renderHeader('WhatsApp群聊', '读取本机 WhatsApp 群聊，设置赛前上游、赛前下游、赛前公司、滚球上游、滚球下游、滚球公司或忽略')")
    expect(page).toContain("renderHeader('皇冠投注中心', '查看皇冠投注明细')")
    expect(page).toContain("renderHeader('赛前对账中心', '查看赛前群订单明细')")
    expect(page).toContain("renderHeader('滚球对账中心', '查看滚球群订单明细')")
    expect(page).toContain("renderHeader('Excel报表', '每天生成的完整账目文件')")
  })

  it('uses requested bill center columns and split reconciliation pages', () => {
    expect(page).toContain("if (clean.startsWith('/bookkeeping/prematch/reconciliation')) return 'prematchReconciliation'")
    expect(page).toContain("if (clean.startsWith('/bookkeeping/rolling/reconciliation')) return 'rollingReconciliation'")
    expect(page).toContain("pageKey === 'rolling' || pageKey === 'rollingReconciliation' ? 'rolling' : 'prematch'")
    expect(page).toContain("roleMatchesWorkspace(order.direction as GroupRole, 'prematch')")
    expect(page).toContain("roleMatchesWorkspace(order.direction as GroupRole, 'rolling')")
    expect(page).toContain("{ title: '投注时间', dataIndex: 'createdAt', render: timeText }")
    expect(page).toContain("{ title: '联赛类型', dataIndex: 'leagueName', render: emptyText }")
    expect(page).toContain("{ title: '比赛队伍', render: (_, row) => matchTeamsText(row.homeTeam, row.awayTeam) }")
    expect(page).toContain("{ title: '投注盘口及赔率', render: (_, row) => marketOddsText(row.marketType, row.selectionName, row.oddsValue) }")
    expect(page).toContain("{ title: '投注金额', dataIndex: 'stakeAmount', render: moneyText }")
    expect(page).toContain("{ title: '赛果', dataIndex: 'status', render: emptyText }")
    expect(page).toContain("{ title: '盈亏', dataIndex: 'winLossAmount', render: moneyText }")
    expect(page).toContain("{ title: '投注时间', dataIndex: 'messageTime', render: timeText }")
    expect(page).toContain("{ title: '比赛队伍', render: (_, row) => matchTeamsText(undefined, undefined, row.matchName) }")
    expect(page).toContain("{ title: '投注盘口及赔率', render: (_, row) => marketOddsText(row.marketText, undefined, row.oddsValue) }")
    expect(page).toContain("{ title: '赛果', dataIndex: 'settlementResult', render: emptyText }")
    expect(page).toContain("{ title: '盈亏', render: (_, row) => orderProfitText(row) }")
    expect(page).toContain("{ title: '群名', render: (_, row) => groupNameForOrder(row) }")
    expect(page).not.toContain("const reconciliationColumns")
    expect(page).not.toContain("renderHeader('对账结果'")
  })

  it('adds whatsapp group sync and settlement controls', () => {
    expect(page).toContain('同步本机群聊')
    expect(page).toContain('刷新登录状态')
    expect(page).toContain('QRCode')
    expect(page).toContain('待设置')
    expect(page).toContain('赛前上游')
    expect(page).toContain('赛前下游')
    expect(page).toContain('赛前公司')
    expect(page).toContain('滚球上游')
    expect(page).toContain('滚球下游')
    expect(page).toContain('滚球公司')
    expect(page).toContain('货币')
    expect(page).toContain('汇率')
    expect(page).not.toContain('退水')
    expect(page).not.toContain('退水（格）')
    expect(page).not.toContain('退水比例')
    expect(page).not.toContain('退水方式')
    expect(page).not.toContain('只输退水')
    expect(page).not.toContain('输赢都退')
    expect(page).not.toContain('走水也退')
    expect(page).not.toContain('rebatePoints')
    expect(page).toContain('exchangeRate')
    expect(page).toContain('RMB')
    expect(page).toContain('USDT')
  })

  it('adds telegram group sync and scan controls', () => {
    expect(page).toContain("if (clean.startsWith('/bookkeeping/telegram/groups')) return 'telegramGroups'")
    expect(page).toContain('Telegram群聊')
    expect(page).toContain('读取当前 Telegram 账号已加入的群聊')
    expect(page).toContain('Telegram Chat ID')
    expect(page).toContain('telegramApiConfigForm')
    expect(page).toContain('loadTelegramApiConfig')
    expect(page).toContain('saveTelegramApiConfig')
    expect(page).toContain('name="apiId"')
    expect(page).toContain('name="apiHash"')
    expect(page).toContain('renderTelegramApiQr')
    expect(page).toContain('setInterval')
    expect(page).toContain("telegramStatus?.status !== 'qr_required'")
    expect(page).not.toContain('renderTelegramLoginQr')
    expect(page).toContain('loadTelegramStatus')
    expect(page).toContain('syncTelegramChats')
    expect(page).toContain('scanTelegramMessages')
    expect(page).toContain('telegramStatus')
    expect(page).toContain('telegramGroups')
  })

  it('shows configured upstream downstream and company follow groups on the dashboard', () => {
    expect(page).toContain('群聊配置')
    expect(page).toContain('赛前上游')
    expect(page).toContain('赛前下游')
    expect(page).toContain('赛前公司')
    expect(page).toContain('滚球上游')
    expect(page).toContain('滚球下游')
    expect(page).toContain('滚球公司')
    expect(page).toContain('公司跟单额')
    expect(page).not.toContain('群聊概况')
    expect(page).not.toContain('groupOverviewItems')
    expect(page).not.toContain('groupSettlementColumns')
  })

  it('calls the bookkeeping API namespace', () => {
    expect(api).toContain('bookkeeping:')
    expect(api).toContain('/bookkeeping/dashboard')
    expect(api).toContain('/bookkeeping/crown/accounts/list')
    expect(api).toContain('/bookkeeping/crown/wagers/import')
    expect(api).toContain('/bookkeeping/whatsapp/bootstrap')
    expect(api).toContain('/bookkeeping/whatsapp/status')
    expect(api).toContain('/bookkeeping/whatsapp/chats/sync')
    expect(api).toContain('/bookkeeping/whatsapp/scan')
    expect(api).toContain('/bookkeeping/whatsapp/orders/import')
    expect(api).toContain('/bookkeeping/telegram/groups/list')
    expect(api).toContain('/bookkeeping/telegram/groups/save')
    expect(api).toContain('/bookkeeping/telegram/api-config')
    expect(api).toContain('/bookkeeping/telegram/api-config/save')
    expect(api).toContain('/bookkeeping/telegram/status')
    expect(api).toContain('/bookkeeping/telegram/chats/sync')
    expect(api).toContain('/bookkeeping/telegram/scan')
    expect(api).toContain('/bookkeeping/score-results/titan007/fetch')
    expect(api).toContain('/bookkeeping/tasks/run')
    expect(api).toContain('/bookkeeping/tasks/generated-files/clear')
    expect(api).toContain('/bookkeeping/tasks/${taskId}/download')
    expect(api).toContain('workspaceType?:')
    expect(api).not.toContain('openclaw')
    expect(api).not.toContain('OpenClaw')
  })

  it('wires prematch and rolling scan buttons to the whatsapp reader', () => {
    expect(page).toContain('scanWhatsappMessages')
    expect(page).toContain("workspaceType: 'prematch'")
    expect(page).toContain("workspaceType: 'rolling'")
    expect(page).toContain('扫描完成')
    expect(page).not.toContain("noticeWorkInProgress('扫描群聊')")
    expect(page).not.toContain("noticeWorkInProgress('重新扫描')")
    expect(page).not.toContain("noticeWorkInProgress('扫描滚球群')")
  })
})
